apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: netologygroup/telemetry
      docker:
        dockerfile: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.IMAGE_TAG}}'
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - deploy/k8s/telemetry.yaml
      - deploy/k8s/telemetry-config.yaml
      - deploy/k8s/telemetry-environment.yaml
      - deploy/k8s/telemetry-headless.yaml
